version: '3'
services: 
    node:
        build:
            context: ./app
            dockerfile: "Dockerfile"
        image: "registry.gitlab.com/macducks/express-angular"
        container_name: project-portal
        ports:
            - 4001:80